#######################################################################################################
# Version: 1.1.4                                                                                      #
# By: Xyaafol                                                                                         #
# Commands:                                                                                           #
# /vmreload - Reloads the plugin with settings changed in this file. Requires OP.                     #
#######################################################################################################

enchantments:
  min-villager-levels:
    mending: 4

buying:

selling:
  mending_1:
    restricted: false
    change: false
    item1:
      material: EMERALD
      cost: 64
    uses: 1


  # silk_touch: All configs under this heading effect villagers with silk touch trades.

  silk_touch_1:
    restricted: false
    change: false
    item1:
      material: EMERALD
      cost: 34
    uses: 1


  # fortune_3: All configs under this heading effect villagers with fortune 3 trades.

  fortune_3:
    restricted: false
    change: false
    item1:
      material: EMERALD
      cost: 64
    uses: 1


  # unbreaking_3: All configs under this heading effect villagers with unbreaking 3 trades.

  unbreaking_3:
    restricted: false
    change: false
    item1:
      material: EMERALD
      cost: 64
    uses: 1


  # efficiency_5: All configs under this heading effect villagers with efficiency 5 trades.

  efficiency_5:
    restricted: false
    change: false
    item1:
      material: EMERALD
      cost: 64
    uses: 1


  # efficiency_4: All configs under this heading effect villagers with efficiency 4 trades.

  efficiency_4:
    restricted: false
    change: false
    item1:
      material: EMERALD
      cost: 64
    uses: 1

  CLOCK:
    restricted: false
    change: false
    item1:
      material: EMERALD
      cost: 64
    uses: 1