main: xy.plugins.villagermodifications.VillagerModifications
authors:
  - Jim (NotKatuen)
  - Xy
version: @project.version@
api-version: 1.16
name: VillagerModifications

commands:
  vmreload:
    description: Reload the plugin.yml
    usage: /<command>
    aliases: [vmr]

  vmbook:
    description: Gives the player a copy of the villager trading book. Used for a template for crate rewards.
    usage: /<command>

  vmwhitelist:
    description: Toggles the ability to whitelist villagers by interacting with them.
    usage: /<command>

  vmoff:
    description: Turns off both /vmwhitelist and /vmremove.
    usage: /<command>

  vmremove:
    description: Toggles the ability to remove villagers from the whitelist by interacting with them.
    usage: /<command>
