#######################################################################################################
# Version: 1.1.4                                                                                      #
# By: Xyaafol                                                                                         #
# Commands:                                                                                           #
# /vmreload - Reloads the plugin with settings changed in this file. Requires OP.                     #
#######################################################################################################

# begin: Time in ticks that villagers can be traded from (day starts at 1000 ticks). Set to 2000 by default.
# end: time in ticks that villagers can be traded until (night starts at 13000 ticks). Set to 8999 by default.
# alert: sends a message to the player if enabled to tell them that the villager is ony available during work hours.

Work:
  begin: 2000
  end: 8999


# alert: Sends an alert to the players when they interact with an unavailable villager.
# on: 0 for off, 1 for on.
# message: The alert that will be sent to the player if alert is on.

alert:
  on: false
  message: "This villager is outside of it's work times"

# allVillagers: Value of 0 by default means that only villagers with trades containing restricted books are bound by Work begin and Work end.
#Set to 1 for all villagers to be restricted.
allVillagers: false

buying:

selling:
  mending_1:
    restricted: false
    change: false
    item1:
      material: EMERALD
      cost: 64
    uses: 1


  # silk_touch: All configs under this heading effect villagers with silk touch trades.

  silk_touch_1:
    restricted: false
    change: false
    item1:
      material: EMERALD
      cost: 34
    uses: 1


  # fortune_3: All configs under this heading effect villagers with fortune 3 trades.

  fortune_3:
    restricted: false
    change: false
    item1:
      material: EMERALD
      cost: 64
    uses: 1


  # unbreaking_3: All configs under this heading effect villagers with unbreaking 3 trades.

  unbreaking_3:
    restricted: false
    change: false
    item1:
      material: EMERALD
      cost: 64
    uses: 1


  # efficiency_5: All configs under this heading effect villagers with efficiency 5 trades.

  efficiency_5:
    restricted: false
    change: false
    item1:
      material: EMERALD
      cost: 64
    uses: 1


  # efficiency_4: All configs under this heading effect villagers with efficiency 4 trades.

  efficiency_4:
    restricted: false
    change: false
    item1:
      material: EMERALD
      cost: 64
    uses: 1

  CLOCK:
    restricted: false
    change: false
    item1:
      material: EMERALD
      cost: 64
    uses: 1