main: xy.plugins.villagermodifications.VillagerModifications
author: Xy
version: 1.0.1
api-version: 1.13
name: VillagerModifications

commands:
  vmreload:
    description: Reload the plugin.yml
    usage: /<command>
    aliases: [vmr]

  vmbook:
    description: Gives the player a copy of the villager trading book. Used for a template for crate rewards.
    usage: /<command>
